# General configuration
version: 1
timezone: Asia/Tokyo # Timezone
# Database configuration
db:
  host: mariaDB
  port: 3306
  user: root
  password: root
  database: deposit_vault
# Lock configuration
lock:
  unit: d # d = day, h = hour, m = minute, s = second
  price: 100 # Price per unit
  max: 7 # Maximum time to lock (unit)